version: '3'
services:
  bulletin:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 0
      DEGREE: 2
    command: './runBulletin.sh'
  node1:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 1
      DEGREE: 2
    command: './runNode.sh'
  node2:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 2
      DEGREE: 2
    command: './runNode.sh'
  node3:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 3
      DEGREE: 2
    command: './runNode.sh'
  node4:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 4
      DEGREE: 2
    command: './runNode.sh'
  node5:
    image: "ejoebstl/churp-cloudlab"
    environment: 
      NODES: bulletin;node1;node2;node3;node4;node5
      PORT: 5000
      MY_INDEX: 5
      DEGREE: 2
    command: './runNode.sh'